name: Build qmlls

on:
  # release nightly on schedule
  schedule:
    - cron: '0 2 * * 1,3,5'
  # also release nightly on manual trigger
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os:   ubuntu-latest
            deps: libgl-dev libglu-dev 'libxcb*-dev' libx11-xcb-dev libxkbcommon-x11-dev libb2-dev libdouble-conversion-dev
            tools: ccache
            install_cmd: sudo apt-get -y install
            configure_flags: -xcb
            debugging_symbols_extension: .dbg
          - name: macos
            os:   macos-latest
            deps:
            tools: ccache
            install_cmd: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install
            configure_flags: -- '-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64'
            debugging_symbols_extension: .dSYM
            unsigned_suffix: -unsigned
          - name: windows
            os:   windows-latest
            install_cmd: choco install
            install_cmd_postfix: --yes --no-progress
            tools: ccache
            configure_flags: -no-feature-sql-psql -no-feature-sql-mysql -no-feature-sql-odbc
            debugging_symbols_extension: .pdb
            executable_extension: .exe
            unsigned_suffix: -unsigned
    runs-on: ${{ matrix.os }}

    steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.30.0"
        ninjaVersion: latest

    - name: prepare Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
    - name: prepare macOS
      if: runner.os == 'macOS'
      run: echo noop
    - name: prepare Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        set >> "%GITHUB_ENV%"

    - uses: actions/checkout@v4
      with:
        path: source
        repository: qt/qt5

    - name: restore ccache
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/ccache
        key:  ccache-${{ matrix.os }}

    - name: install build dependencies
      run:  ${{ matrix.install_cmd }}  ${{ matrix.deps }}  ${{ matrix.install_cmd_postfix }}
      if: matrix.deps != ''
    - name: install compiler tools
      run:  ${{ matrix.install_cmd }}  ${{ matrix.tools }}  ${{ matrix.install_cmd_postfix }}
    - name: configure ccache
      run: |
        ccache --set-config sloppiness=file_macro,time_macros
        ccache --set-config cache_dir='${{ runner.temp }}'/ccache
        ccache --set-config compression=true
        ccache --set-config max_size=1G

    - name: cache repository
      id: cache-repo
      uses: actions/cache@v4
      with:
        path: source
        key: ${{ runner.os }}-repo

    - name: initialize subrepositories
      if: steps.cache-repo.outputs.cache-hit != 'true'
      working-directory: source
      run:  ./init-repository --module-subset=qtdeclarative --mirror="https://code.qt.io/qt/"

    - name: update cached repository
      if: steps.cache-repo.outputs.cache-hit == 'true'
      working-directory: source
      run:  git fetch

    - name: set qtdeclarative to dev and set dependencies via dependencies.yaml
      working-directory: source
      run: | 
        cmake -DSYNC_TO_MODULE="qtdeclarative" -DSYNC_TO_BRANCH="dev" -P cmake/QtSynchronizeRepo.cmake
        echo "Using following SHAs: "
        for i in . qtdeclarative qtbase qtimageformats qtlanguageserver qtshadertools qtsvg; do (cd $i; echo "$i: $(git show HEAD -s --format=oneline)";); done;

    - name: Get current SHA and revision
      id: vars
      working-directory: source/qtdeclarative
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo revision=$(date "+nightly-%Y%m%d") >> $GITHUB_OUTPUT

    - name: cache build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-${{ steps.vars.outputs.sha_short }}-build

    - name: configure and build
      if: steps.cache-build.outputs.cache-hit != 'true'
      run:  |
        mkdir build
        cd build
        ../source/configure -force-debug-info -ccache -no-pch -release -static \
          -force-bundled-libs -submodules qtdeclarative -nomake tests -nomake examples \
          -prefix '${{ runner.temp }}'/install_dir -no-sbom ${{ matrix.configure_flags }}
        ninja qmlls

    - name: Create info file
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        echo -e "commit: ${{ steps.vars.outputs.sha_short }}\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
        > info.txt

    # workarounds because -separate-debug-info is not supported in static builds
    - name: Stripping qmlls binary on linux
      if: matrix.name == 'ubuntu' && steps.cache-build.outputs.cache-hit != 'true'
      run: |
        objcopy --only-keep-debug ./build/qtbase/bin/qmlls ./build/qtbase/bin/qmlls.dbg
        strip ./build/qtbase/bin/qmlls
        objcopy --add-gnu-debuglink=./build/qtbase/bin/qmlls.dbg ./build/qtbase/bin/qmlls

    - name: Stripping qmlls binary on mac
      if: matrix.name == 'macos' && steps.cache-build.outputs.cache-hit != 'true'
      run: |
        dsymutil ./build/qtbase/bin/qmlls -o ./build/qtbase/bin/qmlls.dSYM
        strip ./build/qtbase/bin/qmlls

    - name: Zipping debug symbols and executable
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        7z a qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}-debugsymbols.zip ./build/qtbase/bin/qmlls${{ matrix.debugging_symbols_extension }} info.txt
        7z a qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}${{ matrix.unsigned_suffix }}.zip ./build/qtbase/bin/qmlls${{ matrix.executable_extension }} info.txt

    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        path: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}${{ matrix.unsigned_suffix }}.zip
        name: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}${{ matrix.unsigned_suffix }}.zip

    - name: Upload artefact with debug symbols
      uses: actions/upload-artifact@v4
      with:
        path: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}-debugsymbols.zip
        name: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.revision }}-debugsymbols.zip

  release:
    permissions:
      contents: write
    runs-on: signing-runner
    needs: build
    steps:
    - name: Download artifacts
      id: downloaded_artifacts
      uses: actions/download-artifact@v4
      with:
        path: release

    - name: Get current revision and filenames
      id: vars
      run: |
        echo revision=$(date "+%Y%m%d") >> $GITHUB_OUTPUT
        echo unsigned_macos_archive=$(ls release/qmlls-macos-*-unsigned.zip) >> $GITHUB_OUTPUT
        echo unsigned_windows_archive=$(ls release/qmlls-windows-*-unsigned.zip) >> $GITHUB_OUTPUT

    - name: Sign archives
      id: sign-archives
      uses: TheQtCompanyRnD/SignArchives@v1
      with:
        macos: ${{ steps.vars.outputs.unsigned_macos_archive }}
        win-x64: ${{ steps.vars.outputs.unsigned_windows_archive }}
        jenkins-url: '${{ secrets.JENKINS_URL }}'
        jenkins-user: '${{ secrets.JENKINS_USERNAME }}'
        jenkins-token: '${{ secrets.JENKINS_TOKEN }}'

    - name: Create nightly release
      if: ${{ ! contains(github.ref, 'tags/qmlls-') }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: qmlls-nightly-${{ steps.vars.outputs.revision }}
        draft: false
        prerelease: true
        files: ${{ steps.sign-archives.outputs.macos }} ${{ steps.sign-archives.outputs.win-x64 }} release/*/{windows,macos}*-debugsymbols.zip release/*/qmlls-linux-*.zip

